.ORIG x3000 
AND R4, R4, #0 
AND R5, R5, #0 

TRAP 0x31 ;GET COORDS 
ADD R4, R4, #15 ;16 COUNTER 
ADD R4, R4, #1
ADD R5, R5, #1 ;STARTING POWER 

WRITE 
    LD R6, NUMBER_TO_CONVERT 
    ADD R0, R0, #1 ;ADD 1 TO X 
    AND R6, R6, R5 ;CHECK THE BIT  
    BRnp POSITIVE ;IF 1 PRINT BLOCK IF 0 PRINT AIR 
    LD R3, BLOCK_ID_1
    TRAP 0x34
    BR SKIPPOS

    POSITIVE
    LD R3, BLOCK_ID_2
    TRAP 0x34
    SKIPPOS

    ADD R5, R5, R5 ;TIMES BY 2 TO GET NEXT BIT  
    ADD R4, R4, #-1 ;LOOP 16 TIMES 
BRp WRITE 

HALT 

NUMBER_TO_CONVERT .FILL #1382  ; Note: Please do not change the name of this constant
BLOCK_ID_1 .FILL #0
BLOCK_ID_2 .FILL #1

.END 